# Generated by Django 4.2.3 on 2024-03-06 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_address'),
        ('managers', '0002_alter_manager_options'),
        ('plans', '0003_plan_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanWorklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Список задач для выполнения',
                'verbose_name_plural': 'Списки задач для выполнения',
                'ordering': ('plan', 'worklist'),
            },
        ),
        migrations.CreateModel(
            name='Worklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название работы', max_length=255, verbose_name='Название работы')),
                ('description', models.TextField(blank=True, help_text='Введите описание работы', verbose_name='Описание работы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(editable=False, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Список задач для выполнения',
                'verbose_name_plural': 'Списки задач для выполнения',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AlterModelOptions(
            name='planmanager',
            options={'ordering': ('plan', 'manager'), 'verbose_name': 'Менеджер плана', 'verbose_name_plural': 'Менеджеры плана'},
        ),
        migrations.AlterField(
            model_name='plan',
            name='client',
            field=models.ForeignKey(help_text='Выберите клиента', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='clients.client', verbose_name='Клиент'),
        ),
        migrations.RemoveField(
            model_name='plan',
            name='worklist',
        ),
        migrations.AlterField(
            model_name='planmanager',
            name='manager',
            field=models.ForeignKey(help_text='Выберите менеджера', on_delete=django.db.models.deletion.CASCADE, to='managers.manager', verbose_name='Менеджер'),
        ),
        migrations.AlterField(
            model_name='planmanager',
            name='plan',
            field=models.ForeignKey(help_text='Выберите план', on_delete=django.db.models.deletion.CASCADE, to='plans.plan', verbose_name='План'),
        ),
        migrations.AddConstraint(
            model_name='planmanager',
            constraint=models.UniqueConstraint(fields=('manager', 'plan'), name='unique_manager_plan'),
        ),
        migrations.AddField(
            model_name='planworklist',
            name='plan',
            field=models.ForeignKey(help_text='Выберите план', on_delete=django.db.models.deletion.DO_NOTHING, to='plans.plan', verbose_name='План'),
        ),
        migrations.AddField(
            model_name='planworklist',
            name='worklist',
            field=models.ForeignKey(help_text='Выберите список задач для выполнения', on_delete=django.db.models.deletion.CASCADE, to='plans.worklist', verbose_name='Список задач для выполнения'),
        ),
        migrations.AddField(
            model_name='plan',
            name='worklist',
            field=models.ManyToManyField(help_text='Выберите список задач для выполнения', related_name='plans', through='plans.PlanWorklist', to='plans.worklist', verbose_name='Список задач для выполнения'),
        ),
        migrations.AddConstraint(
            model_name='planworklist',
            constraint=models.UniqueConstraint(fields=('worklist', 'plan'), name='unique_worklist_plan'),
        ),
    ]
