# Generated by Django 4.2.3 on 2024-03-18 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0006_alter_plan_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planworklist',
            name='plan',
            field=models.ForeignKey(help_text='Выберите план', on_delete=django.db.models.deletion.CASCADE, to='plans.plan', verbose_name='План'),
        ),
    ]
