# Generated by Django 4.2.3 on 2024-03-19 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_address_remove_client_address_remove_client_lat_and_more'),
        ('plans', '0007_alter_planworklist_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='address',
            field=models.ForeignKey(help_text='Выберите адрес', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='clients.address', verbose_name='Адрес'),
        ),
    ]
