name: selrad-planner-dev
services:
  celery:
    build: ../backend
    restart: always
    command: bash -c "celery -A config beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler & celery -A config worker -l INFO"
    networks:
      - backend
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
      - logs:/app/logs/
    depends_on:
      - db
      - backend
      - background_tasks
    env_file:
      - ./.env

  background_tasks:
    image: redis:6.0.9-alpine
    restart: always
    networks:
      - backend
    ports:
      - "6380:6379"

  db:
    image: postgis/postgis:13-3.1
    restart: always
    networks:
      - backend
      - shared
    volumes:
      - db_value:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    build: ../backend
    restart: always
    entrypoint: /app/docker/server-entrypoint.sh
    networks:
      - backend
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
      - logs:/app/logs/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    build: ../frontend
    restart: always
    networks:
      - backend
    depends_on:
      - backend
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.3
    restart: always
    ports:
      - 80:80
    networks:
      - backend
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - backend

volumes:
  static_value:
  media_value:
  db_value:
  logs:

networks:
  backend:
    driver: bridge
  shared:
    name: shared_selrad_service_network
    external: true
