# Generated by Django 4.2.3 on 2024-03-23 09:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0002_alter_manager_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='Номер телефона необходимо ввести в формате: "+9999999999". Допускается до 15 цифр', regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
