# Generated by Django 4.2.3 on 2024-03-26 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("managers", "0003_alter_manager_email_alter_manager_phone_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="manager",
            name="email",
        ),
        migrations.RemoveField(
            model_name="manager",
            name="phone_number",
        ),
    ]
