# Generated by Django 4.2.3 on 2024-03-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0004_remove_manager_email_remove_manager_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
