# Generated by Django 4.2.3 on 2024-04-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("managers", "0005_alter_manager_first_name_alter_manager_last_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="manager",
            name="is_hidden",
            field=models.BooleanField(default=False),
        ),
    ]
