# Generated by Django 4.2.3 on 2024-07-27 05:58

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("managers", "0006_manager_is_hidden"),
    ]

    operations = [
        migrations.AddField(
            model_name="manager",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="manager",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="GeoPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lat",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        help_text="Введите широту адреса",
                        max_digits=9,
                        verbose_name="Широта",
                    ),
                ),
                (
                    "lon",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        help_text="Введите долгота адреса",
                        max_digits=9,
                        verbose_name="Долгота",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "point",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True,
                        help_text="Точка адреса",
                        null=True,
                        srid=4326,
                        verbose_name="Точка",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="geo_points",
                        to="managers.manager",
                    ),
                ),
            ],
            options={
                "verbose_name": "Геоточка",
                "verbose_name_plural": "Геоточки",
                "ordering": ["-created_at"],
            },
        ),
    ]
