# Generated by Django 4.2.3 on 2024-07-27 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("managers", "0007_manager_user_geopoint"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Роль",
                "verbose_name_plural": "Роли",
            },
        ),
        migrations.AddField(
            model_name="geopoint",
            name="accuracy",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Точность координат",
                max_digits=9,
                null=True,
                verbose_name="Точность",
            ),
        ),
        migrations.AddField(
            model_name="geopoint",
            name="heading",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Направление движения",
                max_digits=9,
                null=True,
                verbose_name="Направление",
            ),
        ),
        migrations.AddField(
            model_name="geopoint",
            name="speed",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Скорость в метрах в секунду",
                max_digits=9,
                null=True,
                verbose_name="Скорость в м/с",
            ),
        ),
        migrations.AlterField(
            model_name="geopoint",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="geopoints",
                to="managers.manager",
            ),
        ),
        migrations.AddField(
            model_name="manager",
            name="role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managers",
                to="managers.role",
            ),
        ),
    ]
