# Generated by Django 4.2.3 on 2024-07-27 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("managers", "0008_role_geopoint_accuracy_geopoint_heading_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="geopoint",
            name="accuracy",
            field=models.FloatField(
                blank=True,
                help_text="Точность координат",
                null=True,
                verbose_name="Точность",
            ),
        ),
        migrations.AlterField(
            model_name="geopoint",
            name="heading",
            field=models.FloatField(
                blank=True,
                help_text="Направление движения",
                null=True,
                verbose_name="Направление",
            ),
        ),
        migrations.AlterField(
            model_name="geopoint",
            name="speed",
            field=models.FloatField(
                blank=True,
                help_text="Скорость в метрах в секунду",
                null=True,
                verbose_name="Скорость в м/с",
            ),
        ),
    ]
