# Generated by Django 4.2.3 on 2024-07-27 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("managers", "0009_alter_geopoint_accuracy_alter_geopoint_heading_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="manager",
            name="role",
        ),
        migrations.CreateModel(
            name="ManagerRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "manager",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="managers.manager",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="managers.role"
                    ),
                ),
            ],
            options={
                "verbose_name": "Роль менеджера",
                "verbose_name_plural": "Роли менеджеров",
                "ordering": ["-created_at"],
                "unique_together": {("manager", "role")},
            },
        ),
        migrations.AddField(
            model_name="manager",
            name="roles",
            field=models.ManyToManyField(
                blank=True,
                related_name="managers",
                through="managers.ManagerRole",
                to="managers.role",
            ),
        ),
    ]
