# Generated by Django 4.2.3 on 2024-08-13 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("managers", "0010_remove_manager_role_managerrole_manager_roles"),
    ]

    operations = [
        migrations.RenameField(
            model_name="geopoint",
            old_name="lat",
            new_name="latitude",
        ),
        migrations.RenameField(
            model_name="geopoint",
            old_name="lon",
            new_name="longitude",
        ),
    ]
