# Generated by Django 4.2.3 on 2024-08-21 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("managers", "0011_rename_lat_geopoint_latitude_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="manager",
            old_name="first_name",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="manager",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="manager",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="manager",
            name="roles",
        ),
        migrations.RemoveField(
            model_name="manager",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="manager",
            name="is_driver",
            field=models.BooleanField(
                default=False,
                help_text="Является ли менеджер водителем",
                verbose_name="Водитель",
            ),
        ),
        migrations.AddField(
            model_name="manager",
            name="is_keeper",
            field=models.BooleanField(
                default=False,
                help_text="Является ли менеджер кладовщиком",
                verbose_name="Кладовщик",
            ),
        ),
        migrations.AddField(
            model_name="manager",
            name="is_manager",
            field=models.BooleanField(
                default=False,
                help_text="Является ли менеджер менеджером",
                verbose_name="Менеджер",
            ),
        ),
        migrations.AlterField(
            model_name="geopoint",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="geopoints",
                to="managers.manager",
            ),
        ),
        migrations.AlterField(
            model_name="manager",
            name="is_hidden",
            field=models.BooleanField(
                default=False, help_text="Скрыть менеджера", verbose_name="Скрыть"
            ),
        ),
        migrations.DeleteModel(
            name="ManagerRole",
        ),
        migrations.DeleteModel(
            name="Role",
        ),
    ]
