# Generated by Django 4.2.3 on 2024-08-21 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("managers", "0012_rename_first_name_manager_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="manager",
            old_name="is_keeper",
            new_name="is_warehouser",
        ),
    ]
