# Generated by Django 4.2.3 on 2024-11-08 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("managers", "0013_rename_is_keeper_manager_is_warehouser"),
    ]

    operations = [
        migrations.AddField(
            model_name="manager",
            name="is_accountant",
            field=models.BooleanField(
                default=False,
                help_text="Является ли менеджер бухгалтером",
                verbose_name="Бухгалтрер",
            ),
        ),
    ]
