# Generated by Django 4.2.3 on 2024-12-20 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0016_alter_manager_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='payment',
            field=models.IntegerField(default=0, help_text='Введите выплату менеджеру в (₸)', verbose_name='Выплаты менеджеру в (₸)'),
        ),
    ]
