# Generated by Django 4.2.3 on 2025-07-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0017_alter_manager_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='telegram_user_id',
            field=models.IntegerField(blank=True, help_text='Телеграмм id пользователя', null=True, verbose_name='Телеграмм id'),
        ),
    ]
