# Generated by Django 4.2.3 on 2025-07-09 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0018_manager_telegram_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manager',
            old_name='telegram_user_id',
            new_name='tg_user_id',
        ),
    ]
