# Generated by Django 4.2.3 on 2025-07-22 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0019_rename_telegram_user_id_manager_tg_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manager',
            options={'ordering': ('-pk',), 'permissions': [('view_settings', 'Can view settings'), ('view_payments_section', 'Can view payments section (in settings)'), ('can_send_photos_telegram', 'Can send photos in telegram'), ('can_preview_photos_telegram', 'Can preview photos in telegram')], 'verbose_name': 'Менеджер', 'verbose_name_plural': 'Менеджеры'},
        ),
    ]
