# Generated by Django 4.2.3 on 2025-07-26 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0021_alter_manager_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manager',
            options={'ordering': ('-pk',), 'permissions': [('view_settings', 'Can view settings'), ('view_payments_section', 'Can view payments section (in settings)'), ('can_send_photos_telegram', 'Can send photos in telegram'), ('can_preview_photos_telegram', 'Can preview photos in telegram'), ('can_send_old_photos', 'Can upload photos on old tasks'), ('can_view_all_tasks', 'Can view all tasks')], 'verbose_name': 'Менеджер', 'verbose_name_plural': 'Менеджеры'},
        ),
    ]
