# Generated by Django 4.2.3 on 2025-07-26 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0022_alter_manager_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='tg_user_id',
            field=models.CharField(blank=True, help_text='Телеграмм id пользователя', max_length=255, null=True, verbose_name='Телеграмм id'),
        ),
    ]
