# Generated by Django 4.2.3 on 2026-07-17 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0026_daily_tracking_permission_geopoint_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='depot_lat',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Широта домашней точки менеджера. Пример: Алматы 43.25, Астана 51.18.', max_digits=9, null=True, verbose_name='Широта (Lat)'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='depot_lon',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Долгота домашней точки менеджера. Пример: Алматы 76.91, Астана 71.40.', max_digits=9, null=True, verbose_name='Долгота (Lon)'),
        ),
    ]
