server {
    listen 80;
    listen [::]:80;
    # listen 443 default_server ssl http2;
    # listen [::]:443 ssl http2;

    # server_name YOUR_SERVER_HOST selrad-pricelist.ddns.net;  # Replace with your actual domain name
    server_name example.org example.org; # Replace with your actual domain name

    client_max_body_size 2G;
    proxy_buffer_size 128k;   # Adjust buffer size based on your application's requirements
    proxy_buffers 4 256k;     # Use larger buffer sizes for improved performance
    proxy_read_timeout 300;
    proxy_connect_timeout 300;
    proxy_send_timeout 300;

    location / {
        try_files $uri @proxy_api;
    }

    location @proxy_api {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://frontend:3000;
    }

    location /admin/ {
        proxy_pass http://backend:8000/admin/;
    }

    location /api/ {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        # Use a trailing slash for consistency
        proxy_pass http://backend:8000/api/;
    }

    location /media/ {
        alias /var/html/media/;  # Use "alias" instead of "root" for better performance
    }

    location /static/ {
        alias /var/html/static/;
        expires 7d;              # Cache static files in client's browser for 7 days
        access_log off;          # Disable access logs for static files
    }

    # Add any other server configurations here as needed
    # Error handling
    error_page 404 /404.html;
    error_page 500 502 503 504 /50x.html;

    location = /50x.html {
        root /var/www/html;
    }
}
