# Generated by Django 4.2.3 on 2024-08-14 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("managers", "0011_rename_lat_geopoint_latitude_and_more"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("plans", "0025_workitem_show_on_main_page"),
    ]

    operations = [
        migrations.CreateModel(
            name="BaseWorkItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Выберите менеджера который выполнил",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="completed_work_items",
                        to="managers.manager",
                        verbose_name="Менеджер",
                    ),
                ),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "work_item",
                    models.ForeignKey(
                        help_text="Выберите список задач для выполнения",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="plans.workitem",
                        verbose_name="Список задач для выполнения",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "baseworkitem_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="work_items.baseworkitem",
                    ),
                ),
                ("box_count", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("print", "печать"),
                            ("redoing", "переделка"),
                            ("other", "прочее"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Отгрузка",
                "verbose_name_plural": "Отгрузки",
                "ordering": ("-created_at",),
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("work_items.baseworkitem",),
        ),
    ]
