# Generated by Django 4.2.3 on 2024-08-14 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("work_items", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="baseworkitem",
            options={
                "base_manager_name": "objects",
                "ordering": ("-created_at",),
                "verbose_name": "Базовый элемент работы",
                "verbose_name_plural": "Базовые элементы работы",
            },
        ),
    ]
