# Generated by Django 4.2.3 on 2024-08-14 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work_items", "0002_alter_baseworkitem_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipment",
            name="box_count",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
