# Generated by Django 4.2.3 on 2024-08-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work_items", "0003_alter_shipment_box_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="baseworkitem",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Дата обновления"
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("print", "Печать"),
                    ("redoing", "Переделка"),
                    ("other", "Прочее"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
