# Generated by Django 4.2.3 on 2024-09-18 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work_items", "0004_baseworkitem_updated_at_alter_shipment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="time_since_last_arrival",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Время с момента последнего прихода (time since last update on box_count)",
            ),
        ),
    ]
