# Generated by Django 4.2.3 on 2024-09-18 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("work_items", "0005_shipment_time_since_last_arrival"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shipment",
            old_name="time_since_last_arrival",
            new_name="time_since_last_box_arrival",
        ),
    ]
