# Generated by Django 4.2.3 on 2024-11-08 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "work_items",
            "0006_rename_time_since_last_arrival_shipment_time_since_last_box_arrival",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Return",
            fields=[
                (
                    "baseworkitem_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="work_items.baseworkitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Возврат",
                "verbose_name_plural": "Возвраты",
                "ordering": ("-created_at",),
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("work_items.baseworkitem",),
        ),
    ]
