# Generated by Django 4.2.3 on 2025-07-09 05:14

from django.db import migrations, models
import django.db.models.deletion
import work_items.models


class Migration(migrations.Migration):

    dependencies = [
        ('work_items', '0007_return'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('baseworkitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='work_items.baseworkitem')),
                ('tg_photo_batch_before_message_ids', models.JSONField(default=work_items.models.tg_photos_default, verbose_name='Обьект id сообщении, где key это id группы альбомы или id фотки, а value это список message_id')),
                ('tg_photo_batch_after_message_ids', models.JSONField(default=work_items.models.tg_photos_default, verbose_name='Обьект id сообщении, где key это id группы альбомы или id фотки, а value это список message_id')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фотки',
                'ordering': ('-created_at',),
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('work_items.baseworkitem',),
        ),
    ]
