# Generated by Django 4.2.3 on 2025-07-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_items', '0008_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='tg_from_chat_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Чат из которого сообщение были полученны'),
        ),
    ]
