# Generated by Django 4.2.3 on 2025-07-28 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_items', '0009_photo_tg_from_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='tg_from_chat_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Чат из которого сообщение были полученны'),
        ),
    ]
