# Generated by Django 4.2.3 on 2024-03-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('uuid', models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID')),
                ('assigned_date', models.DateField(help_text='Выберите время назначения', max_length=255, verbose_name='Время назначения')),
                ('worklist', models.CharField(choices=[('shipment', 'отгрузка'), ('layout', 'выкладка'), ('photo', 'фото'), ('refund', 'возврат'), ('other', 'прочее')], help_text='Выберите список задач для выполнения', max_length=255, verbose_name='Список задач для выполнения')),
                ('shipment_cost', models.DecimalField(decimal_places=2, help_text='Ввидите сумму отгрузки', max_digits=10, verbose_name='Сумма отгрузки')),
                ('is_completed', models.BooleanField(default=False, help_text='Отметьте, если план выполнен', verbose_name='Статус выполнения')),
                ('comment', models.TextField(blank=True, help_text='Ввидите доп комментарии', verbose_name='Комментарии')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(editable=False, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'План',
                'verbose_name_plural': 'Планы',
                'ordering': ['-assigned_date', '-created_at'],
            },
        ),
    ]
