# Generated by Django 4.2.3 on 2024-04-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="shipment_cost",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Ввидите сумму отгрузки",
                max_digits=15,
                verbose_name="Сумма отгрузки",
            ),
        ),
    ]
