# Generated by Django 4.2.3 on 2024-03-03 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0001_initial'),
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('manager', models.ForeignKey(help_text='Выберите менеджера', on_delete=django.db.models.deletion.DO_NOTHING, to='managers.manager', verbose_name='Менеджер')),
                ('plan', models.ForeignKey(help_text='Выберите план', on_delete=django.db.models.deletion.DO_NOTHING, to='plans.plan', verbose_name='План')),
            ],
        ),
        migrations.AddField(
            model_name='plan',
            name='managers',
            field=models.ManyToManyField(help_text='Выберите менеджеров для плана', related_name='plans', through='plans.PlanManager', to='managers.manager', verbose_name='Менеджеры плана'),
        ),
    ]
