# Generated by Django 4.2.3 on 2024-03-03 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('plans', '0002_planmanager_plan_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='client',
            field=models.ForeignKey(help_text='Выберите клиента', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='plans', to='clients.client', verbose_name='Клиент'),
        ),
    ]
