# Generated by Django 4.2.3 on 2024-04-05 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0011_remove_client_address"),
        ("plans", "0002_alter_plan_shipment_cost"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="address",
            field=models.ForeignKey(
                help_text="Выберите адрес",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plans",
                to="clients.address",
                verbose_name="Адрес",
            ),
        ),
    ]
