# Generated by Django 4.2.3 on 2024-04-05 22:35

from django.db import migrations


def import_addresses(apps, schema_editor):
    """Import addresses from clients to plans."""

    Plan = apps.get_model("plans", "Plan")

    for plan in Plan.objects.all():
        plan.address = plan.client.addresses.first()
        plan.save()


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0003_plan_address"),
    ]

    operations = [migrations.RunPython(import_addresses)]
