# Generated by Django 4.2.3 on 2024-04-20 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0004_auto_20240405_2235"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plan",
            name="address",
        ),
    ]
