# Generated by Django 4.2.3 on 2024-03-06 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_planworklist_worklist_alter_planmanager_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='planmanager',
            name='unique_manager_plan',
        ),
        migrations.RemoveConstraint(
            model_name='planworklist',
            name='unique_worklist_plan',
        ),
    ]
