# Generated by Django 4.2.3 on 2024-05-01 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0005_remove_plan_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="box_count",
            field=models.IntegerField(
                blank=True,
                help_text="Введите количество коробок",
                null=True,
                verbose_name="Количество коробок",
            ),
        ),
    ]
