# Generated by Django 4.2.3 on 2024-03-06 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0005_remove_planmanager_unique_manager_plan_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['assigned_date', '-created_at'], 'verbose_name': 'План', 'verbose_name_plural': 'Планы'},
        ),
    ]
