# Generated by Django 4.2.3 on 2024-05-07 10:24

from django.db import migrations, models
import plans.models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0007_auto_20240501_1111"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="shipment_cost_formula",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Введите формулу стоимости отгрузки",
                max_length=255,
                null=True,
                validators=[plans.models.validate_sum_string],
                verbose_name="Формула стоимости отгрузки",
            ),
        ),
    ]
