# Generated by Django 4.2.3 on 2024-05-07 10:22

from django.db import migrations


def default_shipment_cost_formula(apps, schema_editor):
    """Set the default value for the shipment_cost_formula field."""
    Plan = apps.get_model("plans", "Plan")

    for plan in Plan.objects.all():
        plan.shipment_cost_formula = f"{plan.shipment_cost}"
        plan.save()


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0008_plan_shipment_cost_formula"),
    ]

    operations = [migrations.RunPython(default_shipment_cost_formula)]
