# Generated by Django 4.2.3 on 2024-03-19 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0008_plan_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planmanager',
            name='created_at',
        ),
    ]
