# Generated by Django 4.2.3 on 2024-05-07 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0009_auto_20240507_1022"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plan",
            name="shipment_cost",
        ),
    ]
