# Generated by Django 4.2.3 on 2024-03-26 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0009_remove_planmanager_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='address',
        ),
    ]
