# Generated by Django 4.2.3 on 2024-03-27 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0010_remove_plan_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='is_completed',
        ),
    ]
