# Generated by Django 4.2.3 on 2024-05-12 14:09

from django.db import migrations


def add_custom_permissions(apps, schema_editor):
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")

    content_type = ContentType.objects.get_for_model(apps.get_model("plans", "Plan"))

    Permission.objects.get_or_create(
        codename="export_plans",
        name="Can export plans",
        content_type=content_type,
    )
    Permission.objects.get_or_create(
        codename="export_report",
        name="Can export report",
        content_type=content_type,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0010_remove_plan_shipment_cost"),
    ]

    operations = [migrations.RunPython(add_custom_permissions)]
