# Generated by Django 4.2.3 on 2024-05-12 19:33

from django.db import migrations, models
import plans.models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0011_auto_20240512_1409"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="plan",
            options={
                "ordering": ["assigned_date", "-created_at"],
                "permissions": [
                    ("export_plans", "Can export plans"),
                    ("change_old_plan", "Can change old plan"),
                    ("export_report", "Can export report"),
                ],
                "verbose_name": "План",
                "verbose_name_plural": "Планы",
            },
        ),
        migrations.AlterField(
            model_name="plan",
            name="shipment_cost_formula",
            field=models.CharField(
                blank=True,
                default="0",
                help_text="Введите формулу стоимости отгрузки",
                max_length=255,
                validators=[plans.models.validate_sum_string],
                verbose_name="Формула стоимости отгрузки",
            ),
        ),
    ]
