# Generated by Django 4.2.3 on 2024-05-12 19:41

from django.db import migrations, models
import plans.models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0012_alter_plan_options_alter_plan_shipment_cost_formula"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="shipment_cost_formula",
            field=models.CharField(
                blank=True,
                default="0",
                help_text="Введите формулу стоимости отгрузки",
                max_length=255,
                null=True,
                validators=[plans.models.validate_sum_string],
                verbose_name="Формула стоимости отгрузки",
            ),
        ),
    ]
