# Generated by Django 4.2.3 on 2024-05-13 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0013_alter_plan_shipment_cost_formula"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="plan",
            options={
                "ordering": ["assigned_date", "-created_at"],
                "permissions": [
                    ("export_plans", "Can export plans"),
                    ("change_old_plan", "Can change old plan"),
                    ("delete_old_plan", "Can delete old plan"),
                    ("export_report", "Can export report"),
                ],
                "verbose_name": "План",
                "verbose_name_plural": "Планы",
            },
        ),
    ]
