# Generated by Django 4.2.3 on 2024-05-20 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0014_alter_plan_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="worklist",
            name="meta_name",
            field=models.CharField(
                blank=True,
                help_text="Введите мета название работы",
                max_length=255,
                verbose_name="Мета название работы",
            ),
        ),
    ]
