# Generated by Django 4.2.3 on 2024-07-27 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("managers", "0007_manager_user_geopoint"),
        ("plans", "0015_worklist_meta_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите статус",
                        max_length=255,
                        verbose_name="Статус",
                    ),
                ),
            ],
            options={
                "verbose_name": "Статус",
                "verbose_name_plural": "Статусы",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="planworklist",
            name="completed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберите менеджера",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="completed_plan_worklists",
                to="managers.manager",
                verbose_name="Менеджер",
            ),
        ),
        migrations.CreateModel(
            name="WorklistStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        help_text="Выберите статус",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plans.status",
                        verbose_name="Статус",
                    ),
                ),
                (
                    "worklist",
                    models.ForeignKey(
                        help_text="Выберите список задач для выполнения",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plans.worklist",
                        verbose_name="Список задач для выполнения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Статус списка задач",
                "verbose_name_plural": "Статусы списка задач",
                "ordering": ("worklist", "status"),
            },
        ),
        migrations.AddField(
            model_name="planworklist",
            name="status",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберите статус",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="plans.status",
                verbose_name="Статус",
            ),
        ),
        migrations.AddField(
            model_name="worklist",
            name="statuses",
            field=models.ManyToManyField(
                help_text="Выберите статусы",
                related_name="worklists",
                through="plans.WorklistStatus",
                to="plans.status",
                verbose_name="Статусы",
            ),
        ),
    ]
