# Generated by Django 4.2.3 on 2024-07-30 16:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0016_status_planworklist_completed_by_workliststatus_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="planworklist",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Дата создания",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="planworklist",
            name="updated_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="Дата обновления",
            ),
            preserve_default=False,
        ),
    ]
