# Generated by Django 4.2.3 on 2024-08-12 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0017_planworklist_created_at_planworklist_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planworklist",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Дата создания"
            ),
        ),
        migrations.AlterField(
            model_name="planworklist",
            name="updated_at",
            field=models.DateTimeField(
                blank=True, editable=False, null=True, verbose_name="Дата обновления"
            ),
        ),
    ]
