# Generated by Django 4.2.3 on 2024-08-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0018_alter_planworklist_created_at_and_more"),
    ]

    operations = [
        migrations.RenameModel("worklist", "WorkItem"),
        migrations.AlterField(
            model_name="plan",
            name="worklist",
            field=models.ManyToManyField(
                through="plans.PlanWorklist",
                to="plans.WorkItem",
            ),
        ),
        migrations.RenameField(
            "plan",
            "worklist",
            "work_items",
        ),
        migrations.RenameField(
            "planworklist",
            "worklist",
            "work_item",
        ),
        migrations.RenameField(
            "workliststatus",
            "worklist",
            "work_item",
        ),
    ]
