# Generated by Django 4.2.3 on 2024-08-13 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0019_worklist2workitem"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="planworklist",
            options={
                "ordering": ("-plan", "work_item"),
                "verbose_name": "Список задач для выполнения",
                "verbose_name_plural": "Списки задач для выполнения",
            },
        ),
        migrations.AlterModelOptions(
            name="workliststatus",
            options={
                "ordering": ("work_item", "status"),
                "verbose_name": "Статус списка задач",
                "verbose_name_plural": "Статусы списка задач",
            },
        ),
        migrations.AlterField(
            model_name="plan",
            name="work_items",
            field=models.ManyToManyField(
                help_text="Выберите список задач для выполнения",
                related_name="plans",
                through="plans.PlanWorklist",
                to="plans.workitem",
                verbose_name="Список задач для выполнения",
            ),
        ),
        migrations.AlterField(
            model_name="workitem",
            name="statuses",
            field=models.ManyToManyField(
                help_text="Выберите статусы",
                related_name="work_items",
                through="plans.WorklistStatus",
                to="plans.status",
                verbose_name="Статусы",
            ),
        ),
    ]
