# Generated by Django 4.2.3 on 2024-08-13 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("managers", "0011_rename_lat_geopoint_latitude_and_more"),
        ("plans", "0020_alter_planworklist_options_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PlanWorklist",
            new_name="PlanWorkItem",
        ),
        migrations.RenameModel(
            old_name="WorklistStatus",
            new_name="WorkItemStatus",
        ),
    ]
