# Generated by Django 4.2.3 on 2024-08-13 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("plans", "0022_workitem_content_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workitemstatus",
            name="status",
        ),
        migrations.RemoveField(
            model_name="workitemstatus",
            name="work_item",
        ),
        migrations.AlterModelOptions(
            name="plan",
            options={
                "ordering": ["-assigned_date", "-created_at"],
                "permissions": [
                    ("export_plans", "Can export plans"),
                    ("change_old_plan", "Can change old plan"),
                    ("delete_old_plan", "Can delete old plan"),
                    ("export_report", "Can export report"),
                ],
                "verbose_name": "План",
                "verbose_name_plural": "Планы",
            },
        ),
        migrations.AlterModelOptions(
            name="planworkitem",
            options={},
        ),
        migrations.RemoveField(
            model_name="planworkitem",
            name="completed_by",
        ),
        migrations.RemoveField(
            model_name="planworkitem",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="planworkitem",
            name="status",
        ),
        migrations.RemoveField(
            model_name="planworkitem",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="workitem",
            name="statuses",
        ),
        migrations.RemoveField(
            model_name="workitem",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="planworkitem",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="planworkitem",
            name="object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="workitem",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to=models.Q(
                    ("app_label", "work_items"), ("model", "shipment")
                ),
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddIndex(
            model_name="planworkitem",
            index=models.Index(
                fields=["plan", "work_item"], name="plans_planw_plan_id_bddff3_idx"
            ),
        ),
        migrations.DeleteModel(
            name="Status",
        ),
        migrations.DeleteModel(
            name="WorkItemStatus",
        ),
    ]
