# Generated by Django 4.2.3 on 2024-08-13 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0023_remove_workitemstatus_status_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="planworkitem",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="plans_planw_content_20b393_idx",
            ),
        ),
    ]
