# Generated by Django 4.2.3 on 2024-08-14 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0024_planworkitem_plans_planw_content_20b393_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="workitem",
            name="show_on_main_page",
            field=models.BooleanField(
                default=False,
                help_text="Отображать на главной странице мобильного приложения (selrad app)",
                verbose_name="На главной странице мобильного приложения (selrad app)",
            ),
        ),
    ]
