# Generated by Django 4.2.3 on 2024-08-19 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0025_workitem_show_on_main_page"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="planmanager",
            constraint=models.UniqueConstraint(
                fields=("plan", "manager"), name="unique_plan_manager"
            ),
        ),
        migrations.AddConstraint(
            model_name="planworkitem",
            constraint=models.UniqueConstraint(
                fields=("plan", "work_item"), name="unique_plan_work_item"
            ),
        ),
    ]
