# Generated by Django 4.2.3 on 2024-08-21 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0026_planmanager_unique_plan_manager_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workitem",
            name="description",
        ),
        migrations.RemoveField(
            model_name="workitem",
            name="meta_name",
        ),
    ]
