# Generated by Django 4.2.3 on 2024-08-21 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0027_remove_workitem_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workitem",
            name="show_on_main_page",
        ),
    ]
