# Generated by Django 4.2.3 on 2024-08-22 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0028_remove_workitem_show_on_main_page"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="plan",
            options={
                "ordering": ["-assigned_date", "-created_at"],
                "permissions": [
                    ("export_plans", "Can export plans"),
                    ("change_old_plan", "Can change old plan"),
                    ("delete_old_plan", "Can delete old plan"),
                    ("export_report", "Can export report"),
                    ("get_dispatch_list", "Can export dispatch list"),
                ],
                "verbose_name": "План",
                "verbose_name_plural": "Планы",
            },
        ),
    ]
