# Generated by Django 4.2.3 on 2024-09-18 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0029_alter_plan_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="plan",
            options={
                "ordering": ["-assigned_date", "-created_at"],
                "permissions": [
                    ("export_plans", "Can export plans"),
                    ("change_old_plan", "Can change old plan"),
                    ("delete_old_plan", "Can delete old plan"),
                    ("export_report", "Can export report"),
                    ("get_dispatch_list", "Can export dispatch list"),
                    ("get_dispatch_report", "Can export dispatch report"),
                ],
                "verbose_name": "План",
                "verbose_name_plural": "Планы",
            },
        ),
        migrations.AddField(
            model_name="plan",
            name="time_since_last_dispatch",
            field=models.DateTimeField(
                blank=True,
                help_text="Количество времени, прошедшее с момента последней отправки отчёта.",
                null=True,
                verbose_name="Время с момента последней отправки диспетчерского листа",
            ),
        ),
    ]
