# Generated by Django 4.2.3 on 2024-11-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0030_alter_plan_options_plan_time_since_last_dispatch"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="accountant_comment",
            field=models.TextField(
                blank=True,
                help_text="Ввидите бугалтера комментарии",
                verbose_name="Комментарии бугалтера",
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="invoice_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата накладной"
            ),
        ),
    ]
