# Generated by Django 4.2.3 on 2024-11-08 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("plans", "0031_plan_accountant_comment_plan_invoice_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="plan",
            options={
                "ordering": ["-assigned_date", "-created_at"],
                "permissions": [
                    ("export_plans", "Can export plans"),
                    ("add_old_plan", "Can add old plan"),
                    ("change_old_plan", "Can change old plan"),
                    ("delete_old_plan", "Can delete old plan"),
                    ("export_report", "Can export report"),
                    ("get_dispatch_list", "Can export dispatch list"),
                    ("get_dispatch_report", "Can export dispatch report"),
                ],
                "verbose_name": "План",
                "verbose_name_plural": "Планы",
            },
        ),
        migrations.AlterField(
            model_name="plan",
            name="accountant_comment",
            field=models.TextField(
                blank=True,
                help_text="Ввидите бухгалтера комментарии",
                verbose_name="Комментарии бухгалтера",
            ),
        ),
        migrations.AlterField(
            model_name="workitem",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to=models.Q(
                    models.Q(("app_label", "work_items"), ("model", "shipment")),
                    models.Q(("app_label", "work_items"), ("model", "return")),
                    _connector="OR",
                ),
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
    ]
