# Generated by Django 4.2.3 on 2024-11-08 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0032_alter_plan_options_alter_plan_accountant_comment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="invoice_date",
            field=models.DateField(
                blank=True,
                help_text="Выберите время назначения",
                max_length=255,
                null=True,
                verbose_name="Время назначения",
            ),
        ),
    ]
