# Generated by Django 4.2.3 on 2024-11-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0033_alter_plan_invoice_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="invoice_date",
            field=models.DateField(
                blank=True,
                help_text="Выберите время бухгалтера",
                max_length=255,
                null=True,
                verbose_name="Время Бухгалтера",
            ),
        ),
    ]
