# Generated by Django 4.2.3 on 2024-11-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0034_alter_plan_invoice_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plan",
            name="time_since_last_dispatch",
        ),
        migrations.AddField(
            model_name="plan",
            name="time_since_first_dispatch",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Время с момента первой отправки диспетчерского листа",
            ),
        ),
    ]
