# Generated by Django 4.2.3 on 2024-12-25 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0036_paymentregistry_paymentregistry_unique_date_manager"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="is_permanent",
            field=models.BooleanField(default=False, verbose_name=""),
        ),
    ]
