# Generated by Django 4.2.3 on 2024-12-25 08:09

from django.db import migrations
from datetime import timedelta
from django.utils import timezone


class Migration(migrations.Migration):

    def alter_permanent_for_old_plans(apps, schema_editor):
        plan_model = apps.get_model("plans", "Plan")

        now = timezone.now()
        now = now + timedelta(days=0 - now.weekday() - 1)

        plans = plan_model.objects.filter(assigned_date__lte=now)
        plans.update(is_permanent=True)

    dependencies = [
        ("plans", "0037_plan_is_permanent"),
    ]

    operations = [
        migrations.RunPython(alter_permanent_for_old_plans),
    ]
