# Generated by Django 4.2.3 on 2024-12-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0038_auto_20241225_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='is_permanent',
            field=models.BooleanField(default=False, help_text='перманентный план', verbose_name='перманентный план'),
        ),
    ]
