# Generated by Django 4.2.3 on 2025-01-04 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0040_alter_paymentregistry_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['-assigned_date', '-created_at'], 'permissions': [('export_plans', 'Can export plans'), ('add_old_plan', 'Can add old plan'), ('change_old_plan', 'Can change old plan'), ('delete_old_plan', 'Can delete old plan'), ('export_report', 'Can export report'), ('get_dispatch_list', 'Can export dispatch list'), ('get_dispatch_report', 'Can export dispatch report'), ('export_payment_report', 'Can export payment report')], 'verbose_name': 'План', 'verbose_name_plural': 'Планы'},
        ),
    ]
