# Generated by Django 4.2.3 on 2025-07-09 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('plans', '0041_alter_plan_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workitem',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('app_label', 'work_items'), ('model', 'shipment')), models.Q(('app_label', 'work_items'), ('model', 'return')), models.Q(('app_label', 'work_items'), ('model', 'photo')), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
