# Generated by Django 4.2.3 on 2025-07-09 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0042_alter_workitem_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='workitem',
            name='meta_name',
            field=models.CharField(blank=True, help_text='Введите название работы на англ', max_length=255, null=True, verbose_name='Название работы на англ'),
        ),
    ]
