# Generated by Django 4.2.3 on 2024-03-03 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(help_text='Введите адрес клмента', max_length=255, verbose_name='Адрес клиента'),
        ),
    ]
