# Generated by Django 4.2.3 on 2024-03-19 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0003_client_lat_client_lon"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "street",
                    models.CharField(
                        help_text="Введите адрес клмента",
                        max_length=255,
                        verbose_name="Адрес клиента",
                    ),
                ),
                (
                    "lat",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        help_text="Введите широту адреса",
                        max_digits=9,
                        verbose_name="Широта",
                    ),
                ),
                (
                    "lon",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        help_text="Введите долгота адреса",
                        max_digits=9,
                        verbose_name="Долгота",
                    ),
                ),
            ],
            options={
                "verbose_name": "Адрес",
                "verbose_name_plural": "Адреса",
                "ordering": ["street"],
            },
        ),
        migrations.RemoveField(
            model_name="client",
            name="address",
        ),
        migrations.RemoveField(
            model_name="client",
            name="lat",
        ),
        migrations.RemoveField(
            model_name="client",
            name="lon",
        ),
        migrations.CreateModel(
            name="ClientAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client",
                        to="clients.address",
                        verbose_name="Адрес",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="address",
                        to="clients.client",
                        verbose_name="Клиент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Адрес клиента",
                "verbose_name_plural": "Адреса клиентов",
                "ordering": ["client"],
            },
        ),
        migrations.AddField(
            model_name="client",
            name="addresses",
            field=models.ManyToManyField(
                related_name="clients",
                through="clients.ClientAddress",
                to="clients.address",
                verbose_name="Адреса клиента",
            ),
        ),
    ]
