# Generated by Django 4.2.3 on 2024-03-26 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_address_created_at_address_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='addresses',
        ),
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.ForeignKey(blank=True, help_text='Выберите адрес клиента', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='clients.address', verbose_name='Адрес клиента'),
        ),
        migrations.DeleteModel(
            name='ClientAddress',
        ),
    ]
