# Generated by Django 4.2.3 on 2024-04-01 14:08

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0006_remove_client_addresses_client_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="point",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True,
                help_text="Точка адреса",
                null=True,
                srid=4326,
                verbose_name="Точка",
            ),
        ),
    ]
