# Generated by Django 4.2.3 on 2024-04-05 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0008_populate_address_points"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="address",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберите адрес клиента",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client",
                to="clients.address",
                verbose_name="Адрес клиента",
            ),
        ),
        migrations.CreateModel(
            name="ClientAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address",
                    models.ForeignKey(
                        help_text="Выберите адрес",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_addresses",
                        to="clients.address",
                        verbose_name="Адрес",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        help_text="Выберите клиента",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_addresses",
                        to="clients.client",
                        verbose_name="Клиент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Адрес клиента",
                "verbose_name_plural": "Адреса клиентов",
                "ordering": ["client__name"],
            },
        ),
        migrations.AddField(
            model_name="client",
            name="addresses",
            field=models.ManyToManyField(
                blank=True,
                help_text="Выберите адреса клиента",
                related_name="clients",
                through="clients.ClientAddress",
                to="clients.address",
                verbose_name="Адреса клиента",
            ),
        ),
    ]
