# Generated by Django 4.2.3 on 2024-04-05 13:34

from django.db import migrations


def make_many_addresses(apps, schema_editor):
    """Create many addresses for each client."""

    Client = apps.get_model("clients", "Client")
    Address = apps.get_model("clients", "Address")
    ClientAddress = apps.get_model("clients", "ClientAddress")

    clients = Client.objects.all()
    addresses = Address.objects.all()

    for client in clients:
        ClientAddress.objects.bulk_create(
            [ClientAddress(client=client, address=client.address)]
        )


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0009_alter_client_address_clientaddress_client_addresses"),
    ]

    operations = [
        migrations.RunPython(make_many_addresses),
    ]
