# Generated by Django 4.2.3 on 2024-04-05 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0010_auto_20240405_1334"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="address",
        ),
    ]
