# Generated by Django 4.2.3 on 2024-04-20 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0011_remove_client_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="is_overridden",
            field=models.BooleanField(
                default=False, help_text="Перезаписано", verbose_name="Перезаписано"
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="twogis_link",
            field=models.CharField(
                blank=True,
                help_text="Введите ссылку на 2gis",
                max_length=255,
                null=True,
                verbose_name="Ссылка на 2gis",
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="address",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберите адреса клиента",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="clients_tmp",
                to="clients.address",
                verbose_name="Адреса клиента",
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="is_hidden_on_map",
            field=models.BooleanField(
                default=False,
                help_text="Скрыть клиента на карте",
                verbose_name="Скрыть на карте",
            ),
        ),
    ]
