# Generated by Django 4.2.3 on 2024-04-20 12:53

from django.db import migrations


def make_o2m_address_client(apps, schema_editor):
    """Make One To Many relationship between Address and Client"""
    Client = apps.get_model("clients", "Client")
    Address = apps.get_model("clients", "Address")

    for client in Client.objects.all():
        addresses = client.addresses.all()

        if addresses.count() == 1:
            address = addresses.first()
            client.address = address
            client.save()
        else:
            for address in addresses:
                # Create a new client with the same data
                new_client = Client.objects.get(pk=client.pk)
                new_client.pk = None

                new_client.name = f"{client.name} | {address.street}"
                new_client.address = address
                new_client.save()
            client.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0012_address_is_overridden_address_twogis_link_and_more"),
    ]

    operations = [
        migrations.RunPython(make_o2m_address_client),
    ]
