# Generated by Django 4.2.3 on 2024-04-20 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0013_auto_20240420_1253"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="addresses",
        ),
        migrations.AlterField(
            model_name="client",
            name="address",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберите адрес клиента",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="clients",
                to="clients.address",
                verbose_name="Адрес клиента",
            ),
        ),
        migrations.DeleteModel(
            name="ClientAddress",
        ),
    ]
