# Generated by Django 4.2.3 on 2024-05-28 08:47

from django.db import migrations


def address_points_none_fix(apps, schema_editor):
    Address = apps.get_model("clients", "Address")
    for address in Address.objects.all():
        address.save()


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0014_remove_client_addresses_alter_client_address_and_more"),
    ]

    operations = [migrations.RunPython(address_points_none_fix)]
