# Generated by Django 4.2.3 on 2024-10-10 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0015_auto_20240528_0847"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetaClient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите имя клиента",
                        max_length=255,
                        verbose_name="Имя клиента",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
            ],
            options={
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенты",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="client",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Магазин",
                "verbose_name_plural": "Магазины",
            },
        ),
        migrations.AlterField(
            model_name="address",
            name="street",
            field=models.CharField(
                help_text="Введите адрес магазина",
                max_length=255,
                verbose_name="Адрес магазина",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="address",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберите адрес магазина",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="clients",
                to="clients.address",
                verbose_name="Адрес магазина",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="is_hidden_on_map",
            field=models.BooleanField(
                default=False,
                help_text="Скрыть магазин на карте",
                verbose_name="Скрыть на карте",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="name",
            field=models.CharField(
                help_text="Введите имя клиента",
                max_length=255,
                verbose_name="Имя магазина",
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="meta_client",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберите клиента к магазину",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clients",
                to="clients.metaclient",
                verbose_name="Клиент",
            ),
        ),
    ]
