# Generated by Django 4.2.3 on 2024-10-16 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "clients",
            "0016_metaclient_alter_client_options_alter_address_street_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={
                "ordering": ["-created_at"],
                "permissions": [("export_compare_years", "Can export compare report")],
                "verbose_name": "Магазин",
                "verbose_name_plural": "Магазины",
            },
        ),
    ]
