# Generated by Django 4.2.3 on 2024-12-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0017_alter_client_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Адрес",
                "verbose_name_plural": "Адреса",
            },
        ),
        migrations.RemoveField(
            model_name="address",
            name="is_overridden",
        ),
        migrations.AlterField(
            model_name="client",
            name="name",
            field=models.CharField(
                help_text="Введите имя магазина",
                max_length=255,
                verbose_name="Имя магазина",
            ),
        ),
    ]
